//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.02 at 05:14:34 PM EDT 
//


package org.rlcommunity.environments.octopus.config;

//import javax.xml.bind.annotation.XmlAccessType;
//import javax.xml.bind.annotation.XmlAccessorType;
//import javax.xml.bind.annotation.XmlRootElement;
//import javax.xml.bind.annotation.XmlType;
import org.rlcommunity.environments.octopus.config.Config;
import org.rlcommunity.environments.octopus.config.ConstantSet;
import org.rlcommunity.environments.octopus.config.EnvSpec;


/**
 * <p>Java class for config element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="config">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;all>
 *           &lt;element name="constants" type="{}ConstantSet"/>
 *           &lt;element name="environment" type="{}EnvSpec"/>
 *         &lt;/all>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
public class Config {

    protected ConstantSet constants;
    protected EnvSpec environment;

    /**
     * Gets the value of the constants property.
     * 
     * @return
     *     possible object is
     *     {@link ConstantSet }
     *     
     */
    public ConstantSet getConstants() {
        return constants;
    }

    /**
     * Sets the value of the constants property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstantSet }
     *     
     */
    public void setConstants(ConstantSet value) {
        this.constants = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link EnvSpec }
     *     
     */
    public EnvSpec getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvSpec }
     *     
     */
    public void setEnvironment(EnvSpec value) {
        this.environment = value;
    }

}
