//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.02 at 05:14:34 PM EDT 
//


package org.rlcommunity.environments.octopus.config;

import java.util.ArrayList;
import java.util.List;

import org.rlcommunity.environments.octopus.config.NodeSpec;


/**
 * <p>Java class for NodeSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="mass" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="position" use="required" type="{}Duple" />
 *       &lt;attribute name="velocity" type="{}Duple" default="0 0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class NodeSpec {

    protected double mass;
    protected List<Double> position;
    protected List<Double> velocity;

    public NodeSpec(){}
        public NodeSpec(double mass, List<Double> position, List<Double> velocity){
            this.mass=mass;
            this.position=position;
            this.velocity=velocity;
        }
        public NodeSpec(double mass, double[] position, double[] velocity){
            this.mass=mass;
            
            this.position=new ArrayList<Double>();
            for (double d : position)this.position.add(d);

            this.velocity=new ArrayList<Double>();
            for (double d : velocity)this.velocity.add(d);

        }

    /**
     * Gets the value of the mass property.
     * 
     */
    public double getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     */
    public void setMass(double value) {
        this.mass = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the position property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getPosition() {
        if (position == null) {
            position = new ArrayList<Double>();
        }
        return this.position;
    }

    /**
     * Gets the value of the velocity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the velocity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVelocity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getVelocity() {
        if (velocity == null) {
            velocity = new ArrayList<Double>();
        }
        return this.velocity;
    }

}
