//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.02 at 05:14:34 PM EDT 
//


package org.rlcommunity.environments.octopus.config;

import org.rlcommunity.environments.octopus.config.ChoiceSpec;
import org.rlcommunity.environments.octopus.config.ObjectiveSetSpec;


/**
 * <p>Java class for ChoiceSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChoiceSpec">
 *   &lt;complexContent>
 *     &lt;extension base="{}ObjectiveSetSpec">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class ChoiceSpec
    extends ObjectiveSetSpec
{
        public ChoiceSpec(ObjectiveSpec[] objectiveArray){
            super(objectiveArray);
                    System.err.println(getClass()+" is broken, not implemented correctly");

        }


}
