//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.02 at 05:14:34 PM EDT 
//


package org.rlcommunity.environments.octopus.config;

import org.rlcommunity.environments.octopus.config.ArmSpec;
import org.rlcommunity.environments.octopus.config.EnvSpec;
import org.rlcommunity.environments.octopus.config.FoodTaskDef;
import org.rlcommunity.environments.octopus.config.TargetTaskDef;
import org.rlcommunity.environments.octopus.config.TaskDef;
import java.math.BigInteger;


/**
 * <p>Java class for EnvSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnvSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="arm" type="{}ArmSpec"/>
 *         &lt;element ref="{}task"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class EnvSpec {

    protected ArmSpec arm;
    
    public EnvSpec(){
        arm=new ArmSpec();
    }
//    @XmlElementRef(name = "task", type = JAXBElement.class)
//    protected JAXBElement<? extends TaskDef> task;

    /**
     * Gets the value of the arm property.
     * 
     * @return
     *     possible object is
     *     {@link ArmSpec }
     *     
     */
    public ArmSpec getArm() {
        return arm;
    }

    /**
     * Sets the value of the arm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArmSpec }
     *     
     */
    public void setArm(ArmSpec value) {
        this.arm = value;
    }

    /**
     * Gets the value of the task property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TaskDef }{@code >}
     *     {@link JAXBElement }{@code <}{@link FoodTaskDef }{@code >}
     *     {@link JAXBElement }{@code <}{@link TargetTaskDef }{@code >}
     *     
     */
    
     public TaskDef getTask(){
         BigInteger timeLimit=new BigInteger("100000");
         double stepReward=-1.0;
         
//
//Can learn this with a fat kernel
//TargetSpec targSpec=new TargetSpec(new double[]{6.0d, -2.0d}, 20.0d);
         TargetSpec targSpec=new TargetSpec(new double[]{6.0d, 5.0d}, 20.0d);
         
         TaskDef theTask=new TargetTaskDef(targSpec,timeLimit,stepReward);
         return theTask;
         
//         TargetSpec targSpec2=new TargetSpec(new double[]{10.5d, 1.5d}, 1.0d);
//         TargetSpec targSpec3=new TargetSpec(new double[]{10.5d, -0.5d}, 3.0d);
         
         
         
//<targetTask timeLimit="10000" stepReward="0">
//    <choice>
//        <sequence>
//            <target position="9 1.5" reward="2" />
//            <target position="10.5 1.5" reward="1" />
//        </sequence>
//        <target position="10 -0.5" reward="3" />
//    </choice>
//</targetTask>
                 
             
         }
//    public JAXBElement<? extends TaskDef> getTask() {
//        return task;
//    }

    /**
     * Sets the value of the task property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TaskDef }{@code >}
     *     {@link JAXBElement }{@code <}{@link FoodTaskDef }{@code >}
     *     {@link JAXBElement }{@code <}{@link TargetTaskDef }{@code >}
     *     
     */
//    public void setTask(JAXBElement<? extends TaskDef> value) {
//        this.task = ((JAXBElement<? extends TaskDef> ) value);
//    }

}
