//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.02 at 05:14:34 PM EDT 
//


package org.rlcommunity.environments.octopus.config;

import org.rlcommunity.environments.octopus.config.FoodSpec;
import org.rlcommunity.environments.octopus.config.NodeSpec;


/**
 * <p>Java class for FoodSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FoodSpec">
 *   &lt;complexContent>
 *     &lt;extension base="{}NodeSpec">
 *       &lt;attribute name="reward" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class FoodSpec
    extends NodeSpec
{
    protected Double reward;

    /**
     * Gets the value of the reward property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getReward() {
        return reward;
    }

    /**
     * Sets the value of the reward property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setReward(Double value) {
        this.reward = value;
    }

}
