//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.02 at 05:14:34 PM EDT 
//


package org.rlcommunity.environments.octopus.config;

import java.util.ArrayList;
import java.util.List;
import org.rlcommunity.environments.octopus.config.FoodSpec;
import org.rlcommunity.environments.octopus.config.FoodTaskDef;
import org.rlcommunity.environments.octopus.config.MouthSpec;
import org.rlcommunity.environments.octopus.config.TaskDef;
import java.math.BigInteger;


/**
 * <p>Java class for FoodTaskDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FoodTaskDef">
 *   &lt;complexContent>
 *     &lt;extension base="{}TaskDef">
 *       &lt;sequence>
 *         &lt;element name="mouth" type="{}MouthSpec"/>
 *         &lt;element name="food" type="{}FoodSpec" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class FoodTaskDef
    extends TaskDef
{

    protected MouthSpec mouth;
    protected List<FoodSpec> food;

        public FoodTaskDef(BigInteger timeLimit, Double stepReward){
            super(timeLimit,stepReward);
            System.err.println(this.getClass()+" is broken, not implemented right");
        }

    /**
     * Gets the value of the mouth property.
     * 
     * @return
     *     possible object is
     *     {@link MouthSpec }
     *     
     */
    public MouthSpec getMouth() {
        return mouth;
    }

    /**
     * Sets the value of the mouth property.
     * 
     * @param value
     *     allowed object is
     *     {@link MouthSpec }
     *     
     */
    public void setMouth(MouthSpec value) {
        this.mouth = value;
    }

    /**
     * Gets the value of the food property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the food property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFood().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FoodSpec }
     * 
     * 
     */
    public List<FoodSpec> getFood() {
        if (food == null) {
            food = new ArrayList<FoodSpec>();
        }
        return this.food;
    }

}
