//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.02 at 05:14:34 PM EDT 
//


package org.rlcommunity.environments.octopus.config;

import javax.xml.namespace.QName;
import org.rlcommunity.environments.octopus.config.ArmSpec;
import org.rlcommunity.environments.octopus.config.ChoiceSpec;
import org.rlcommunity.environments.octopus.config.Config;
import org.rlcommunity.environments.octopus.config.ConstantSet;
import org.rlcommunity.environments.octopus.config.EnvSpec;
import org.rlcommunity.environments.octopus.config.FoodSpec;
import org.rlcommunity.environments.octopus.config.FoodTaskDef;
import org.rlcommunity.environments.octopus.config.MouthSpec;
import org.rlcommunity.environments.octopus.config.NodePairSpec;
import org.rlcommunity.environments.octopus.config.NodeSpec;
import org.rlcommunity.environments.octopus.config.ObjectFactory;
import org.rlcommunity.environments.octopus.config.ObjectiveSetSpec;
import org.rlcommunity.environments.octopus.config.ObjectiveSpec;
import org.rlcommunity.environments.octopus.config.SequenceSpec;
import org.rlcommunity.environments.octopus.config.TargetSpec;
import org.rlcommunity.environments.octopus.config.TargetTaskDef;
import org.rlcommunity.environments.octopus.config.TaskDef;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory {

    private final static QName _FoodTask_QNAME = new QName("", "foodTask");
    private final static QName _Target_QNAME = new QName("", "target");
    private final static QName _Choice_QNAME = new QName("", "choice");
    private final static QName _TargetTask_QNAME = new QName("", "targetTask");
    private final static QName _Task_QNAME = new QName("", "task");
    private final static QName _Sequence_QNAME = new QName("", "sequence");
    private final static QName _Objective_QNAME = new QName("", "objective");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NodeSpec }
     * 
     */
    public NodeSpec createNodeSpec() {
        return new NodeSpec();
    }

    /**
     * Create an instance of {@link ArmSpec }
     * 
     */
    public ArmSpec createArmSpec() {
        return new ArmSpec();
    }

    /**
     * Create an instance of {@link EnvSpec }
     * 
     */
    public EnvSpec createEnvSpec() {
        return new EnvSpec();
    }

    /**
     * Create an instance of {@link ConstantSet }
     * 
     */
    public ConstantSet createConstantSet() {
        return new ConstantSet();
    }

    /**
     * Create an instance of {@link FoodTaskDef }
     * 
     */
    public FoodTaskDef createFoodTaskDef() {
        return null;//new FoodTaskDef();
    }

    /**
     * Create an instance of {@link SequenceSpec }
     * 
     */
    public SequenceSpec createSequenceSpec() {
        return null;//new SequenceSpec();
    }

    /**
     * Create an instance of {@link ObjectiveSetSpec }
     * 
     */
    public ObjectiveSetSpec createObjectiveSetSpec() {
        return null;//new ObjectiveSetSpec();
    }

    /**
     * Create an instance of {@link TargetTaskDef }
     * 
     */
    public TargetTaskDef createTargetTaskDef() {
        return null;//new TargetTaskDef();
    }

    /**
     * Create an instance of {@link TargetSpec }
     * 
     */
    public TargetSpec createTargetSpec() {
        return null;//new TargetSpec();
    }

    /**
     * Create an instance of {@link MouthSpec }
     * 
     */
    public MouthSpec createMouthSpec() {
        return new MouthSpec();
    }

    /**
     * Create an instance of {@link NodePairSpec }
     * 
     */
    public NodePairSpec createNodePairSpec() {
        return new NodePairSpec();
    }

    /**
     * Create an instance of {@link ChoiceSpec }
     * 
     */
    public ChoiceSpec createChoiceSpec() {
        return null;//new ChoiceSpec();
    }

    /**
     * Create an instance of {@link FoodSpec }
     * 
     */
    public FoodSpec createFoodSpec() {
        return new FoodSpec();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FoodTaskDef }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "", name = "foodTask", substitutionHeadNamespace = "", substitutionHeadName = "task")
//    public JAXBElement<FoodTaskDef> createFoodTask(FoodTaskDef value) {
//        return new JAXBElement<FoodTaskDef>(_FoodTask_QNAME, FoodTaskDef.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link TargetSpec }{@code >}}
//     * 
//     */
//    @XmlElementDecl(namespace = "", name = "target", substitutionHeadNamespace = "", substitutionHeadName = "objective")
//    public JAXBElement<TargetSpec> createTarget(TargetSpec value) {
//        return new JAXBElement<TargetSpec>(_Target_QNAME, TargetSpec.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link ChoiceSpec }{@code >}}
//     * 
//     */
//    @XmlElementDecl(namespace = "", name = "choice", substitutionHeadNamespace = "", substitutionHeadName = "objective")
//    public JAXBElement<ChoiceSpec> createChoice(ChoiceSpec value) {
//        return new JAXBElement<ChoiceSpec>(_Choice_QNAME, ChoiceSpec.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link TargetTaskDef }{@code >}}
//     * 
//     */
//    @XmlElementDecl(namespace = "", name = "targetTask", substitutionHeadNamespace = "", substitutionHeadName = "task")
//    public JAXBElement<TargetTaskDef> createTargetTask(TargetTaskDef value) {
//        return new JAXBElement<TargetTaskDef>(_TargetTask_QNAME, TargetTaskDef.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link TaskDef }{@code >}}
//     * 
//     */
//    @XmlElementDecl(namespace = "", name = "task")
//    public JAXBElement<TaskDef> createTask(TaskDef value) {
//        return new JAXBElement<TaskDef>(_Task_QNAME, TaskDef.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link SequenceSpec }{@code >}}
//     * 
//     */
//    @XmlElementDecl(namespace = "", name = "sequence", substitutionHeadNamespace = "", substitutionHeadName = "objective")
//    public JAXBElement<SequenceSpec> createSequence(SequenceSpec value) {
//        return new JAXBElement<SequenceSpec>(_Sequence_QNAME, SequenceSpec.class, null, value);
//    }
//
//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectiveSpec }{@code >}}
//     * 
//     */
//    @XmlElementDecl(namespace = "", name = "objective")
//    public JAXBElement<ObjectiveSpec> createObjective(ObjectiveSpec value) {
//        return new JAXBElement<ObjectiveSpec>(_Objective_QNAME, ObjectiveSpec.class, null, value);
//    }

}
